### ISSUE TITLE
Support with VS Code LaTeX-Workshop plugin

### ISSUE THREAD

**Issue by codingdave** [shiblon/latex-makefile#192]
Hi,

I use this Makefile for 15 years and want to thank you very much for this, as its been a very helpful and reliable partner for me. I am not an expert user because I write 2 or 3 Latex documents a year. Nowadays I use VS Code with the [Latex-Workshop](https://github.com/James-Yu/LaTeX-Workshop) plugin most of the time but also combine it with using this makefile. And building works well! The only issue I have is with the files vcsode creates during building, they are not handled by clean, namely

    *.fdb_latexmk 
    *.synctex.gz

 Do you think removal of those autogenerated files can be added into the Makefile clean target?

Kind regards
Dave

**Comment by shiblon** [comment]
You are too kind! And I'm glad it has worked for you, that's the only news that matters to me! Happy that my little side project is useful to more than just myself. It was a labor of love, but also of distraction (I made this while working on my dissertation, and sometimes it provided just the break I needed).

Note that you can add clean targets yourself by creating an ini file with a variable setting in it, just to test that it works as intended first. We can also add these to the main Makefile after checking on that:

Create a Makefile.ini in the same directory as Makefile, add the following line to it:

cleanextra := *.fdb_latexmk *.synctex.gz

If that works for you, we're all set, and I can work to figure out the cleanest way of adding these to the main file. Please don't hesitate to reopen this as an issue and we'll get you sorted.

**Comment by codingdave** [comment]
I am happy to make you happy by just telling you how helpful your work was in my life :-)

I have created the Makefile.ini as suggested but it does not work. I have looked into the Makefile and the term "Makefile.ini" exists and so the file will get included but I can't find the term cleanextra in it. I am using version  2.2.1-alpha9.

I have also tried with only 1 of the 2 entries and not succeeded. Does it work on your end?

**Comment by shiblon** [comment]
I just tried it with the latest Makefile from github, with the changes to Makefile.ini as indicated, and (I hate saying this, but) it works for me :)

Let's see if we can get to the bottom of it for you, though.

**Comment by codingdave** [comment]
I am sorry, yes, I did not use the latest one in this directory (went into the wrong one. Sorry).
It works like a charm with the Makefile.ini.
Thanks  you!

**Comment by shiblon** [comment]
Change e7c3433bf4285142c3c3053edeb62891c16c6954
Change 35cef1023fde057650ebe4c70a97d1e426570699

Should be good to go with the above changes, and won't need .ini anymore (changes are in main branch, so just redownload `Makefile`)

Thanks so much for filing the issue. And I'm always looking for collaborators who actually use LaTeX, so if you have any interest in continuing to point out flaws, help with making tests better, etc., I'm always receptive.
